os: linux
dist: trusty
sudo: false

language: cpp

addons:
  apt:
    packages:
      - clang
      - g++-4.8
      - gcc-4.8
      - ninja-build
      - liblzma-dev
      - libz-dev
      - docbook2x
    sources:
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - ubuntu-toolchain-r-test

env: 
  matrix:
    - BUILD_TYPE=Release CC_COMPILER=clang-5.0 CXX_COMPILER=clang++5.0
    - BUILD_TYPE=Debug CC_COMPILER=clang-5.0 CXX_COMPILER=clang++5.0
    - BUILD_TYPE=Release CC_COMPILER=gcc-4.8 CXX_COMPILER=g++-4.8
    - BUILD_TYPE=Debug CC_COMPILER=gcc-4.8 CXX_COMPILER=g++-4.8

install:
  - mkdir -p deps && cd deps
  - travis_retry wget --no-check-certificate --quiet -O - https://cmake.org/files/v3.7/cmake-3.7.1-Linux-x86_64.tar.gz | tar --strip-components=1 -xz
  - export PATH=${TRAVIS_BUILD_DIR}/deps/bin:${PATH}
  - cd -

before_script:
  - apt-cache search clang
  - travis_retry wget --quiet -O - https://raw.githubusercontent.com/cpplint/cpplint/master/cpplint.py | python - --recursive src examples
  - mkdir -p build && cd build
  - rm -rf *
  - cmake .. -GNinja -DLIB_PROTO_MUTATOR_WITH_ASAN=ON -DCMAKE_C_COMPILER=${CC_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script:
  - ninja && ctest -V -j8
